INSERT INTO TOWNS (`ID`, `NAME`) VALUES (1, 'Krakow');
INSERT INTO TOWNS (`ID`, `NAME`) VALUES (2, 'Warszawa');
INSERT INTO TOWNS (`ID`, `NAME`) VALUES (3, 'Poznan');



INSERT INTO CAMPAIGNS (`ID`, `BID_AMOUNT`, `CAMPAIGN_FUND`, `NAME`, `RADIUS`, `STATUS`, `TOWN_ID`) VALUES (1, 1000, 'Nike Fund', 'Nike', 300, true, 1);
INSERT INTO KEY_WORDS (`CAMPAIGN_ID`, `KEY_WORD`) VALUES (1, 'Nike');
INSERT INTO KEY_WORDS (`CAMPAIGN_ID`, `KEY_WORD`) VALUES (1, 'Big');

INSERT INTO CAMPAIGNS (`ID`, `BID_AMOUNT`, `CAMPAIGN_FUND`, `NAME`, `RADIUS`, `STATUS`, `TOWN_ID`) VALUES (2, 200, 'Adidas Fund', 'Adidas', 500, false, 2);
INSERT INTO KEY_WORDS (`CAMPAIGN_ID`, `KEY_WORD`) VALUES (2, 'Adidas');
INSERT INTO KEY_WORDS (`CAMPAIGN_ID`, `KEY_WORD`) VALUES (2, 'Small');

INSERT INTO CAMPAIGNS (`ID`, `BID_AMOUNT`, `CAMPAIGN_FUND`, `NAME`, `RADIUS`, `STATUS`, `TOWN_ID`) VALUES (3, 300, 'Toyota Fund', 'Toyota', 700, true, 3);
INSERT INTO KEY_WORDS (`CAMPAIGN_ID`, `KEY_WORD`) VALUES (3, 'Toyota');
INSERT INTO KEY_WORDS (`CAMPAIGN_ID`, `KEY_WORD`) VALUES (3, 'Medium');